### ISSUE TITLE
Sensu dashboard throws an error when attempting to view a check config that doesn't exist

### ISSUE THREAD

**Issue by calebhailey** [sensu/web#180]
## Expected Behavior

Sensu dashboard doesn't throw an error when viewing non-existent check configs; similar to how we handle this for entities: 

![image](https://user-images.githubusercontent.com/141373/62315888-2e122a00-b44b-11e9-90b4-4a32e235e817.png)

Here's the error: 

```
Error: Check with name 'foo', not found.
    at EditCheckDialog (http://localhost:3000/static/js/app_b2df.js:1:587482)
    at hg (http://localhost:3000/static/js/vendor_e112.js:157:53108)
    at Mg (http://localhost:3000/static/js/vendor_e112.js:157:59913)
    at Tg (http://localhost:3000/static/js/vendor_e112.js:157:66598)
    at bi (http://localhost:3000/static/js/vendor_e112.js:157:90700)
    at ci (http://localhost:3000/static/js/vendor_e112.js:157:91084)
    at Di (http://localhost:3000/static/js/vendor_e112.js:157:97974)
    at Yh (http://localhost:3000/static/js/vendor_e112.js:157:97354)
    at Xh (http://localhost:3000/static/js/vendor_e112.js:157:96375)
    at qf (http://localhost:3000/static/js/vendor_e112.js:157:95246)
    at wg (http://localhost:3000/static/js/vendor_e112.js:157:56094)
    at Object.next (http://localhost:3000/static/js/app_b2df.js:1:1066687)
    at notifySubscription (http://localhost:3000/static/js/vendor_e112.js:104:38122)
    at onNotify (http://localhost:3000/static/js/vendor_e112.js:104:38738)
    at SubscriptionObserver.next (http://localhost:3000/static/js/vendor_e112.js:104:39552)
    at http://localhost:3000/static/js/vendor_e112.js:89:118379
```

## Current Behavior

Sensu dashboard throws an error: 

![image](https://user-images.githubusercontent.com/141373/62315855-1aff5a00-b44b-11e9-9ed2-1544a8272435.png)

## Possible Solution

Same as how we handle 404s for entities. 

## Steps to Reproduce

1. Spin up a fresh Sensu Go backend. 
2. Try to load http://localhost:3000/default/checks/foo 
3. :boom: 

## Context

Users can encounter this error if they are publishing events to on of the Sensu Go /events APIs (via the backend or agent). Viewing the event offers a link to view the check configuration, which may not exist. 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.11.1 (web revision d738763)
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): debian/stretch
* Browser used: chrome

**Comment by jamesdphillips** [comment]
Fixed by sensu/sensu-enterprise-go#585
