### ISSUE TITLE
Apollo throwing Invariant Violation

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/web#247]
Originally reported in Discourse: https://discourse.sensu.io/t/received-error-message-invariant-violation/1636

## Stacktrace

```
Invariant Violation: Invariant Violation
at new InvariantError (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:17:14991)
at invariant (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:17:15178)
at StoreWriter.writeFieldToStore (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:33:74373)
at https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:33:72856
at Array.forEach ()
at StoreWriter.writeSelectionSetToStore (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:33:72714)
at StoreWriter.writeResultToStore (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:33:72192)
at CustomCache.InMemoryCache.write (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:33:77843)
at DataStore.markQueryResult (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:90:220965)
at QueryManager.markQueryResult (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:90:209651)
at https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:90:218642
at Object.next (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:105:28920)
at notifySubscription (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:105:26227)
at onNotify (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:105:26843)
at SubscriptionObserver.next (https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:105:27657)
at https://sensu-dev.sample.example.com/static/js/vendor_bcb1.js:90:203940
```

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/received-error-message-invariant-violation/1636/2
