### ISSUE TITLE
Unexpected Error: "GraphQL error: couldn't list events: resource is invalid: couldn't get events: error decoding token: couldn't decode token: invalid character 'b' after top-level value"

### ISSUE THREAD

**Issue by Oloremo** [sensu/web#336]
## Expected Behavior
The opening dashboard events page is working.

## Current Behavior
Opening Dashboard events page fails with the error:

```
Error: GraphQL error: couldn't list events: resource is invalid: couldn't get events: error decoding token: couldn't decode token: invalid character 'b' after top-level value
    at new ApolloError (http://172.31.30.81:3000/static/js/app_9361.js:2:124730)
    at http://172.31.30.81:3000/static/js/app_9361.js:2:147991
    at http://172.31.30.81:3000/static/js/app_9361.js:2:154452
    at Set.forEach (<anonymous>)
    at http://172.31.30.81:3000/static/js/app_9361.js:2:154428
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (http://172.31.30.81:3000/static/js/app_9361.js:2:154378)
    at http://172.31.30.81:3000/static/js/app_9361.js:2:156493
    at Object.next (http://172.31.30.81:3000/static/js/app_9361.js:2:2241392)
    at notifySubscription (http://172.31.30.81:3000/static/js/app_9361.js:2:2238670)
```

## Steps to Reproduce (for bugs)
See the Context

## Context
So I'm doing a load testing following https://github.com/sensu/sensu-perf that creates a 1000 "fake" agents in ours case.

I tried to add a check to those fake agents with the following definition:
```
sensuctl asset add sensu/sensu-ruby-runtime:0.0.10 -r sensu-ruby-runtime
sensuctl asset add sensu-plugins/sensu-plugins-cpu-checks:4.1.0 -r cpu-checks-plugins
sensuctl check create check-cpu \
  --command 'check-cpu.rb -w 10 -c 90' \
  --interval 60 \
  --subscriptions large_cluster_test_1 \
  --runtime-assets cpu-checks-plugins,sensu-ruby-runtime
```

Something went wrong and I have. that kind of events for all those agents:
```
  ffb1de11-2746-474e-a287-dacc6c271d02   check-cpu   error getting assets for event: error fetching asset: Get : unsupported protocol scheme ""            3   false      2020-09-02 18:08:17 +0000 UTC
```

While that happening I tried to open dashboard and got that error.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.21.0
  sensu/web revision: `b6d7442`
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): Centos 7.6

**Comment by Oloremo** [comment]
Seems to be fixed in 5.21.2
