### ISSUE TITLE
Unexpected Error: "GraphQL error: Panic received in batch function: runtime error: index out of range [35] with length 35"

### ISSUE THREAD

**Issue by anatolijd** [sensu/web#344]
## Expected Behavior
Login into Web UI, switch to non-default namespace.

## Current Behavior
As admin user, I can login to default namespace, which is empty. There are 2 more non-default namespaces confugred - "main" and "test". 
I can switch to "main" namspace without a problem.
As soon as I switch to namespace "test" - I'm getting red pop-up window with the stacktrace (see below).
After that I'm redirected to login form again. 

## Context

**Browser Stack Trace:**
```
Error: GraphQL error: Panic received in batch function: runtime error: index out of range [35] with length 35
    at new t (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:591533)
    at https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:612444
    at https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:618476
    at Set.forEach (<anonymous>)
    at https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:618452
    at Map.forEach (<anonymous>)
    at t.broadcastQueries (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:618402)
    at https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:620316
    at Object.next (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:702766)
    at h (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:700519)
    at v (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:701025)
    at e.value (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:701642)
    at https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:619428
    at f (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:536400)
    at T._settlePromiseFromHandler (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:524717)
    at T._settlePromise (https://sensu-web.acme.com/static/js/vendors~app_8632.js:2:525517)

```
relevant sensu-backend.log:
```
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: {"component":"backend.api","level":"debug","msg":"request authorized by the binding cluster-admin","time":"2020-11-24T16:49:00Z","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"test","resource":"namespaces","resourceName":"test","username":"admin","verb":"get"}}
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: {"component":"apid","duration":"8.380ms","level":"info","method":"POST","msg":"request completed","path":"/graphql","size":91,"status":200,"time":"2020-11-24T16:49:00Z","user":"admin"}
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: {"component":"backend.api","level":"debug","msg":"request authorized by the binding cluster-admin","time":"2020-11-24T16:49:00Z","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"test","resource":"namespaces","resourceName":"test","username":"admin","verb":"get"}}
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: {"component":"rbac","level":"debug","msg":"request authorized by the binding cluster-admin","time":"2020-11-24T16:49:00Z","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"test","resource":"checks","resourceName":"","username":"admin","verb":"list"}}
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: {"component":"rbac","level":"debug","msg":"request authorized by the binding cluster-admin","time":"2020-11-24T16:49:00Z","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"test","resource":"entities","resourceName":"","username":"admin","verb":"list"}}
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: {"component":"etcd","level":"info","msg":"Dataloader: Panic received in batch function:: runtime error: index out of range [26] with length 26\ngoroutine 962341 [running]:\ngithub.com/graph-gophers/dataloader.(*batcher).batch.func1.1(0xc000ae7f60, 0xc0014109c0)\n\t/go/pkg/mod/github.com/graph-gophers/dataloader@v0.0.0-20180104184831-78139374585c/dataloader.go:428 +0xb6\npanic(0x16779c0, 0xc00f76cb80)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/sensu/sensu-go/backend/store/etcd.entitiesFromConfigAndState(0xc000288a00, 0x1a, 0x1a, 0xc000bbc000, 0x1b, 0x1b, 0x0, 0x1a12d20, 0xc000a95da0, 0xc000ae7b20, ...)\n\t/usr/local/src/sensu-go/backend/store/etcd/entity_store.go:240 +0x772\ngithub.com/sensu/sensu-go/backend/store/etcd.(*Store).GetEntities(0xc005d52e40, 0x1a12d20, 0xc000a95da0, 0xc0014119e0, 0x0, 0x0, 0x0, 0x5f3458, 0x16621e0)\n\t/usr/local/src/sensu-go/backend/store/etcd/entity_store.go:233 +0x7da\ngithub.com/sensu/sensu-go/backend/api.(*EntityClient).ListEntities(0xc00c8f2880, 0x1a12d20, 0xc000a95da0, 0x19b61c8, 0x14a6a60, 0xc00b064040, 0x1a12d20, 0xc000a95da0)\n\t/usr/local/src/sensu-go/backend/api/entity.go:145 +0x1d4\ngithub.com/sensu/sensu-go/backend/apid/graphql.loadEntitiesBatchFn.func1(0x1a12d20, 0xc00a201d10, 0xc00b064030, 0x1, 0x1, 0xc009630f00, 0xc000057660, 0x10c5dd8)\n\t/usr/local/src/sensu-go/backend/apid/graphql/dataloader.go:105 +0x162\ngithub.com/graph-gophers/dataloader.(*batcher).batch.func1(0xc000057760, 0xc0014109c0, 0x1a12d20, 0xc00a201d10, 0xc00b064030, 0x1, 0x1, 0xc000ae7f80)\n\t/go/pkg/mod/github.com/graph-gophers/dataloader@v0.0.0-20180104184831-78139374585c/dataloader.go:432 +0xc4\ngithub.com/graph-gophers/dataloader.(*batcher).batch(0xc0014109c0, 0x1a12d20, 0xc00a201d10)\n\t/go/pkg/mod/github.com/graph-gophers/dataloader@v0.0.0-20180104184831-78139374585c/dataloader.go:433 +0x408\ncreated by github.com/graph-gophers/dataloader.(*Loader).Load\n\t/go/pkg/mod/github.com/graph-gophers/dataloader@v0.0.0-20180104184831-78139374585c/dataloader.go:241 +0x5f3\n","pkg":"","time
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: ":"2020-11-24T16:49:00Z"}
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: {"component":"apid.routers","errors":[{"message":"Panic received in batch function: runtime error: index out of range [26] with length 26","locations":[{"line":23,"column":3},{"line":84,"column":3}],"path":["namespace","entities"]}],"level":"error","msg":"error(s) occurred while executing GraphQL operation","time":"2020-11-24T16:49:00Z"}
Nov 24 16:49:00 is-1839b.acme.com sensu-backend[23658]: {"component":"apid","duration":"20.131ms","level":"info","method":"POST","msg":"request completed","path":"/graphql","size":246,"status":200,"time":"2020-11-24T16:49:00Z","user":"admin"}
Nov 24 16:49:01 is-1839b.acme.com sensu-backend[23658]: {"component":"etcd","level":"info","msg":"http: TLS handshake error from 172.20.67.112:32283: EOF\n","pkg":"","time":"2020-11-24T16:49:01Z"}
```

At the same time, I'm not able to list entites in that that one "test" namespace anymore, it fails immediatelt with this err message:
```
# sensuctl enity list --namespace test

Error: Get https://sensu-api.acme.com:8080/api/core/v2/namespaces/test/entities: EOF
```

I can list other objects (user,handler,asset,check,event) in "test" namespace fine,   but not entity.

I can list entity in any other namespace expect "test".

sensu-backend.log for `sensuctl entity list --namespace test`
```
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","error":"EOF","level":"error","msg":"websocket connection error","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","level":"warning","msg":"http: TLS handshake error from 172.20.3.191:18606: EOF","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"etcd","level":"info","msg":"http: TLS handshake error from 172.20.99.107:37376: EOF\n","pkg":"","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"rbac","level":"debug","msg":"request authorized by the binding cluster-admin","time":"2020-11-24T15:58:04Z","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"test","resource":"entities","resourceName":"","username":"admin","verb":"list"}}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"etcd","level":"info","msg":"http: panic serving 172.20.35.188:43590: runtime error: index out of range [35] with length 35\ngoroutine 534625 [running]:\nnet/http.(*conn).serve.func1(0xc005de5c20)\n
\t/usr/local/go/src/net/http/server.go:1767 +0x139\n
panic(0x16779c0, 0xc007719940)\n
\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\n
github.com/sensu/sensu-go/backend/store/etcd.entitiesFromConfigAndState(0xc000bd0000, 0x23, 0x23, 0xc000be6000, 0x24, 0x24, 0x0, 0x1a12d20, 0xc00a6209f0, 0xc00096ea38, ...)\n
\t/usr/local/src/sensu-go/backend/store/etcd/entity_store.go:240 +0x772\n
github.com/sensu/sensu-go/backend/store/etcd.(*Store).GetEntities(0xc006a661e0, 0x1a12d20, 0xc00a6209f0, 0xc00a620a20, 0xc00096ebd0, 0x5f3868, 0xc00a620150, 0x14a3ca0, 0x19b55e8)\n\t
/usr/local/src/sensu-go/backend/store/etcd/entity_store.go:233 +0x7da\n
github.com/sensu/sensu-go/backend/apid/actions.EntityController.List(0x1a18020, 0xc006a661e0, 0x1a285a0, 0xc00f9559b8, 0x1a12d20, 0xc00a6209f0, 0xc00a620a20, 0x150c4a0, 0xc00a620060, 0xc00096ec78, ...)\n\t
/usr/local/src/sensu-go/backend/apid/actions/entities.go:45 +0x62\
ngithub.com/sensu/sensu-go/backend/apid/routers.List.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab600)\n\t
/usr/local/src/sensu-go/backend/apid/routers/lister.go:45 +0x229\n
net/http.HandlerFunc.ServeHTTP(...)\n\t
/usr/local/go/src/net/http/server.go:2007\n
github.com/sensu/sensu-go/backend/apid/routers.listerHandler.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab600)\n\t
/usr/local/src/sensu-go/backend/apid/routers/lister.go:65 +0x61\n
net/http.HandlerFunc.ServeHTTP(0xc006d37fe0, 0x7fef03350200, 0xc00a6202a0, 0xc000aab600)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.Pagination.Then.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab500)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/pagination.go:34 +0x2b7\nnet/http.HandlerFunc.ServeHTTP(0xc006fefca0, 0x7fef03350200, 0xc00a6202a0, 0xc000aab500)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.LimitRequest.Then.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab500)\n\t
/usr/local/src/sensu-go/backend/apid/middlewares/limitrequest.go:28 +0x221\n
net/http.HandlerFunc.ServeHTTP(0xc006fefcc0, 0x7fef03350200, 0xc00a6202a0, 0xc000aab500)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.Authorization.Then.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aab000)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/authorization.go:58 +0x738\nnet/http.HandlerFunc.ServeHTTP(0xc00a620090, 0x7fef03350200, 0xc00a6202a0, 0xc000aab000)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.AuthorizationAttributes.Then.func1(0x7fef03350200, 0xc00a6202a0, 0xc000aaaf00)\n\t
/usr/local/src/sensu-go/backend/apid/middlewares/authorization_attributes.go:102 +0x5c4\nnet/http.HandlerFunc.ServeHTTP(0xc006fefce0, 0x7fef03350200, 0xc00a6202a0, 0xc000aaaf00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.SimpleLogger.Then.func1(0x1a0b5a0, 0xc000b13180, 0xc000aaaf00)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/logging.go:26 +0x205\nnet/http.HandlerFunc.ServeHTTP(0xc006fefd00, 0x1a0b5a0, 0xc000b13180, 0xc000aaaf00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.Authentication.Then.func1(0x1a0b5a0, 0xc000b13180, 0xc000aaae00)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/authentication.go:43 +0x72a\nnet/http.HandlerFunc.ServeHTTP(0xc00a6200c0, 0x1a0b5a0, 0xc000b13180, 0xc000aaae00)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/sensu/sensu-go/backend/apid/middlewares.Namespace.Then.func1(0x1a0b5a0, 0xc000b13180, 0xc000aaad00)\n\t/usr/local/src/sensu-go/backend/apid/middlewares/namespace.go:29 +0x1b4\n
net/http.HandlerFunc.ServeHTTP(0xc006fefd40, 0x1a0b5a0, 0xc000b13180, 0xc000aaad00)\n\t
/usr/local/go/src/net/http/server.go:2007 +0x44\n
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000
Nov 24 15:58:04 is-1840b sensu-backend[6750]: d18900, 0x1a0b5a0, 0xc000b13180, 0xc000aaaa00)\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2\n
net/http.serverHandler.ServeHTTP(0xc005d8b5e0, 0x1a0b5a0, 0xc000b13180, 0xc000aaaa00)\n\t
/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc005de5c20, 0x1a12c60, 0xc00a6b6100)\n\t
/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t
/usr/local/go/src/net/http/server.go:2927 +0x38e\n","pkg":"","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"etcd","level":"info","msg":"http: TLS handshake error from 172.20.3.191:47915: EOF\n","pkg":"","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","error":"EOF","level":"error","msg":"websocket connection error","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","level":"warning","msg":"http: TLS handshake error from 172.20.35.123:62531: EOF","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","error":"EOF","level":"error","msg":"websocket connection error","time":"2020-11-24T15:58:04Z"}
Nov 24 15:58:04 is-1840b sensu-backend[6750]: {"component":"agentd","level":"warning","msg":"http: TLS handshake error from 172.20.35.123:43592: EOF","time":"2020-11-24T15:58:04Z"}
```

In 'test' namespace  I have over 50 agents registered, around 20 checks executed every 60 seconds, and over 1000 events.

Please help to resolve this. 

## Your Environment

* Sensu community version 6.1.3
  sensu/web revision (1.0.3): `c0890b2`
* Installation method : binary compiled from git sources.

**Comment by portertech** [comment]
Duplicate, closing in favour of https://github.com/sensu/sensu-go/issues/4102
